name: Security CI (bWAPP)

on:
  push:
    branches:
      - develop
      - "feature/**"
  pull_request:
    branches:
      - develop

jobs:
  sast-phpstan:
    name: SAST (PHPStan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

      - name: Run PHPStan
        run: |
          ~/.composer/vendor/bin/phpstan analyse . --level=max || true

  secrets-scan:
    name: Secrets Scan (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          report-format: json
          output: gitleaks-report.json
        continue-on-error: true
